### ISSUE TITLE
XPath selectors

### ISSUE THREAD

**Issue by scottlabs** [brianmhunt/casper-chai#21]
Hi,

Is there any way to support selection via XPath?

So something like:

`'//body'.should.be.inDOM`

**Comment by nathanboktae** [comment]
Maybe it could be done like `{ xpath: '//body' }.should.be.inDOM` ?

**Comment by scottlabs** [comment]
I ended up using something close, `{ type: 'xpath', path: '//body' }.should.be.inDOM;`

**Comment by nathanboktae** [comment]
oh yeah that's the format for xpath selectors, right. ok.
