### ISSUE TITLE
PhantomJS v2 does not support coffee out of the box

### ISSUE THREAD

**Issue by ardi-n** [brianmhunt/casper-chai#22]
As stated in a subject, could you distribute compiled version of library and set package.json's main file appropriately?

**Comment by nathanboktae** [comment]
I'd rather just convert it to plain JavaScript and kill the Cakefile too, testing multiple versions of PhantomJS in Travis too. I did it for `mocha-phantomjs-core` that worked well.

Thoughts @brianmhunt?

**Comment by brianmhunt** [comment]
@nathanboktae I'd say go for it :)

**Comment by ardi-n** [comment]
Hi, are you gonna do this or am I supposed to? :)
